### PR TITLE
Updated for Swift 3

### PR DESCRIPTION
**Pull request by daveyostcom**
Also there is some editing of the text for typos, etc.

### CODE REVIEW

**Comment by terhechte** [comment]
Awesome, thanks! Sorry for taking so much time! Thank you so much!

**Comment by daveyostcom** [comment]
You're welcome. It was well worth doing!

**Comment by daveyostcom** [comment]
Btw you should say something in the Changes section.

**Comment by daveyostcom** [comment]
Would you mind squashing my 4 commits into 1?

**Pull request merged**
